import type { AnkiDeck } from './parser';

function deck(id: string, name: string, cards: Array<[string, string]>): AnkiDeck {
  return {
    id: `builtin-${id}`,
    name,
    importedAt: 0,
    cards: cards.map(([front, back], i) => ({
      id: i,
      front,
      back,
      tags: [],
      cardType: 'basic',
    })),
  };
}

export const BUILTIN_DECKS: AnkiDeck[] = [
  deck('world-capitals', '🌍 World Capitals', [
    ['Capital of France', 'Paris'],
    ['Capital of Japan', 'Tokyo'],
    ['Capital of Brazil', 'Brasília'],
    ['Capital of Australia', 'Canberra'],
    ['Capital of Canada', 'Ottawa'],
    ['Capital of Egypt', 'Cairo'],
    ['Capital of India', 'New Delhi'],
    ['Capital of South Africa', 'Pretoria (executive) / Cape Town (legislative) / Bloemfontein (judicial)'],
    ['Capital of Argentina', 'Buenos Aires'],
    ['Capital of Nigeria', 'Abuja'],
    ['Capital of Russia', 'Moscow'],
    ['Capital of China', 'Beijing'],
    ['Capital of Germany', 'Berlin'],
    ['Capital of Mexico', 'Mexico City'],
    ['Capital of Indonesia', 'Jakarta (moving to Nusantara)'],
    ['Capital of Saudi Arabia', 'Riyadh'],
    ['Capital of Turkey', 'Ankara'],
    ['Capital of Kenya', 'Nairobi'],
    ['Capital of Peru', 'Lima'],
    ['Capital of Sweden', 'Stockholm'],
    ['Capital of New Zealand', 'Wellington'],
    ['Capital of Pakistan', 'Islamabad'],
    ['Capital of Ukraine', 'Kyiv'],
    ['Capital of Vietnam', 'Hanoi'],
    ['Capital of Ethiopia', 'Addis Ababa'],
    ['Capital of Colombia', 'Bogotá'],
    ['Capital of Thailand', 'Bangkok'],
    ['Capital of Poland', 'Warsaw'],
    ['Capital of Morocco', 'Rabat'],
    ['Capital of Bangladesh', 'Dhaka'],
  ]),

  deck('periodic-table', '⚗️ Periodic Table Elements', [
    ['Element symbol: H', 'Hydrogen (atomic number 1)'],
    ['Element symbol: He', 'Helium (atomic number 2)'],
    ['Element symbol: Li', 'Lithium (atomic number 3)'],
    ['Element symbol: C', 'Carbon (atomic number 6)'],
    ['Element symbol: N', 'Nitrogen (atomic number 7)'],
    ['Element symbol: O', 'Oxygen (atomic number 8)'],
    ['Element symbol: Na', 'Sodium (atomic number 11) — from Latin "Natrium"'],
    ['Element symbol: Mg', 'Magnesium (atomic number 12)'],
    ['Element symbol: Al', 'Aluminum (atomic number 13)'],
    ['Element symbol: Si', 'Silicon (atomic number 14)'],
    ['Element symbol: K', 'Potassium (atomic number 19) — from Latin "Kalium"'],
    ['Element symbol: Ca', 'Calcium (atomic number 20)'],
    ['Element symbol: Fe', 'Iron (atomic number 26) — from Latin "Ferrum"'],
    ['Element symbol: Cu', 'Copper (atomic number 29) — from Latin "Cuprum"'],
    ['Element symbol: Zn', 'Zinc (atomic number 30)'],
    ['Element symbol: Ag', 'Silver (atomic number 47) — from Latin "Argentum"'],
    ['Element symbol: Sn', 'Tin (atomic number 50) — from Latin "Stannum"'],
    ['Element symbol: Au', 'Gold (atomic number 79) — from Latin "Aurum"'],
    ['Element symbol: Hg', 'Mercury (atomic number 80) — from Latin "Hydrargyrum"'],
    ['Element symbol: Pb', 'Lead (atomic number 82) — from Latin "Plumbum"'],
    ['Element symbol: U', 'Uranium (atomic number 92)'],
    ['Which element has the highest melting point?', 'Tungsten (W) — 3,422 °C'],
    ['Most abundant element in the universe', 'Hydrogen'],
    ['Most abundant element in Earth\'s crust', 'Oxygen'],
    ['The only liquid metal at room temperature', 'Mercury (Hg)'],
  ]),

  deck('scientists', '🔬 Scientists & Discoveries', [
    ['Who developed the theory of general relativity?', 'Albert Einstein (1915)'],
    ['Who discovered penicillin?', 'Alexander Fleming (1928)'],
    ['Who proposed the heliocentric model in 1543?', 'Nicolaus Copernicus'],
    ['Who discovered the structure of DNA?', 'Watson & Crick (1953), using X-ray data from Rosalind Franklin'],
    ['Who formulated the laws of motion and universal gravitation?', 'Isaac Newton'],
    ['Who is the father of modern chemistry?', 'Antoine Lavoisier'],
    ['Who developed the polio vaccine?', 'Jonas Salk (1955)'],
    ['Who discovered radioactivity?', 'Henri Becquerel (1896); further studied by Marie Curie'],
    ['Who proposed the theory of evolution by natural selection?', 'Charles Darwin (1859, On the Origin of Species)'],
    ['Who invented the telephone?', 'Alexander Graham Bell (1876)'],
    ['Who discovered the electron?', 'J.J. Thomson (1897)'],
    ['Who discovered the neutron?', 'James Chadwick (1932)'],
    ['Who developed the germ theory of disease?', 'Louis Pasteur'],
    ['What did Gregor Mendel discover?', 'Laws of heredity / genetics (1860s, using pea plants)'],
    ['Who is credited with inventing the World Wide Web?', 'Tim Berners-Lee (1989)'],
    ['Who developed the first successful airplane?', 'Wright Brothers — Orville & Wilbur (1903)'],
    ['Who proposed quantum mechanics\' uncertainty principle?', 'Werner Heisenberg (1927)'],
    ['What did Edwin Hubble discover?', 'Galaxies exist outside the Milky Way; the universe is expanding'],
    ['Who discovered X-rays?', 'Wilhelm Röntgen (1895)'],
    ['What is the Turing machine?', 'A theoretical model of computation proposed by Alan Turing (1936)'],
  ]),

  deck('literature', '📚 Literature & Authors', [
    ['Who wrote "Don Quixote" (1605)?', 'Miguel de Cervantes — often called the first modern novel'],
    ['Who wrote "Pride and Prejudice" (1813)?', 'Jane Austen'],
    ['Who wrote "Crime and Punishment" (1866)?', 'Fyodor Dostoevsky'],
    ['Who wrote "One Hundred Years of Solitude" (1967)?', 'Gabriel García Márquez — magical realism masterpiece'],
    ['Who wrote "Hamlet", "Macbeth", and "King Lear"?', 'William Shakespeare'],
    ['Who wrote "The Iliad" and "The Odyssey"?', 'Homer (8th century BC)'],
    ['Who wrote "1984" and "Animal Farm"?', 'George Orwell'],
    ['Who wrote "To Kill a Mockingbird" (1960)?', 'Harper Lee'],
    ['Who wrote "The Great Gatsby" (1925)?', 'F. Scott Fitzgerald'],
    ['Who wrote "In Search of Lost Time" (À la recherche du temps perdu)?', 'Marcel Proust'],
    ['Who wrote "Beloved" (1987)?', 'Toni Morrison'],
    ['Who wrote the "Divine Comedy"?', 'Dante Alighieri (14th century)'],
    ['Who wrote "War and Peace"?', 'Leo Tolstoy'],
    ['Who wrote "Faust"?', 'Johann Wolfgang von Goethe'],
    ['Who wrote "Things Fall Apart" (1958)?', 'Chinua Achebe'],
    ['Who wrote "The Metamorphosis" (1915)?', 'Franz Kafka'],
    ['What is magical realism?', 'A literary genre blending realistic narrative with magical elements, prominent in Latin American literature (García Márquez, Borges)'],
    ['Who wrote "Middlemarch" (1871)?', 'George Eliot (Mary Ann Evans)'],
    ['Who wrote "The Canterbury Tales"?', 'Geoffrey Chaucer (14th century)'],
    ['Who wrote "Invisible Man" (1952)?', 'Ralph Ellison'],
  ]),

  deck('world-history', '🏛️ World History Timeline', [
    ['When did World War I begin and end?', '1914–1918'],
    ['When did World War II begin and end?', '1939–1945'],
    ['When did the French Revolution begin?', '1789'],
    ['When did the Roman Empire fall (Western)?', '476 CE — sack of Rome by Odoacer'],
    ['When was the Magna Carta signed?', '1215 — limited English royal power'],
    ['When did the Black Death peak in Europe?', '1347–1351 — killed ~1/3 of Europe\'s population'],
    ['When did Columbus reach the Americas?', '1492'],
    ['When did the printing press become widespread?', 'c. 1450 — Gutenberg\'s movable type'],
    ['When did the Russian Revolution occur?', '1917 — Bolsheviks under Lenin took power'],
    ['When did India gain independence?', '1947'],
    ['When was the United Nations founded?', '1945'],
    ['When did the Berlin Wall fall?', '1989'],
    ['When did the Cold War end?', '1991 — dissolution of the Soviet Union'],
    ['What was the Silk Road?', 'Ancient trade network connecting China to the Mediterranean (2nd century BC–15th century CE)'],
    ['When was the Qin Dynasty (China\'s first unified empire)?', '221–206 BC — Qin Shi Huang first emperor'],
    ['When did the Ottoman Empire end?', '1922 — replaced by the Republic of Turkey in 1923'],
    ['What was the Meiji Restoration?', '1868 — Japan\'s rapid modernization and westernization'],
    ['When did the Atlantic slave trade peak?', '18th century — c. 12 million Africans transported to the Americas'],
    ['When was the Declaration of Independence signed?', '1776'],
    ['What was the Scramble for Africa?', '1880s–1914 — rapid European colonization of Africa'],
  ]),

  deck('math-formulas', '📐 Mathematical Formulas', [
    ['Area of a circle', 'A = πr²'],
    ['Circumference of a circle', 'C = 2πr'],
    ['Pythagorean theorem', 'a² + b² = c² (right triangle, c = hypotenuse)'],
    ['Quadratic formula', 'x = (−b ± √(b²−4ac)) / 2a'],
    ['Area of a triangle', 'A = ½ × base × height'],
    ['Volume of a sphere', 'V = (4/3)πr³'],
    ['Surface area of a sphere', 'SA = 4πr²'],
    ['Volume of a cylinder', 'V = πr²h'],
    ['Distance formula (2D)', 'd = √((x₂−x₁)² + (y₂−y₁)²)'],
    ['Slope of a line', 'm = (y₂−y₁) / (x₂−x₁)'],
    ['Compound interest', 'A = P(1 + r/n)^(nt)'],
    ['Euler\'s identity', 'e^(iπ) + 1 = 0'],
    ['Law of cosines', 'c² = a² + b² − 2ab·cos(C)'],
    ['Sum of interior angles of a polygon', '(n − 2) × 180°'],
    ['Definition of a logarithm', 'log_b(x) = y means b^y = x'],
    ['Difference of squares', 'a² − b² = (a+b)(a−b)'],
    ['Binomial theorem (first terms)', '(a+b)² = a² + 2ab + b²; (a+b)³ = a³ + 3a²b + 3ab² + b³'],
    ['Mean formula', 'Mean = (sum of values) / (number of values)'],
    ['Permutations', 'P(n,r) = n! / (n−r)!'],
    ['Combinations', 'C(n,r) = n! / (r! × (n−r)!)'],
  ]),

  deck('art-history', '🎨 Art Movements & Artists', [
    ['What is Impressionism?', 'Late 19th-century movement capturing light and movement with loose brushwork. Key artists: Monet, Renoir, Degas'],
    ['What is Cubism?', 'Early 20th century; subjects fragmented into geometric shapes. Key artists: Picasso, Braque'],
    ['What is Surrealism?', 'Dream-like imagery, irrational juxtapositions. Key artists: Dalí, Magritte, Ernst'],
    ['Who painted the Sistine Chapel ceiling?', 'Michelangelo (1508–1512)'],
    ['Who painted the "Mona Lisa"?', 'Leonardo da Vinci (c. 1503–1519)'],
    ['Who painted "The Starry Night"?', 'Vincent van Gogh (1889)'],
    ['Who painted "Girl with a Pearl Earring"?', 'Johannes Vermeer (c. 1665)'],
    ['What is the Baroque period?', '17th century; dramatic, ornate style. Key artists: Caravaggio, Rubens, Rembrandt'],
    ['What is Abstract Expressionism?', 'Post-WWII American movement; emotion through spontaneous, non-representational forms. Key artists: Pollock, de Kooning'],
    ['Who painted "The Birth of Venus"?', 'Sandro Botticelli (c. 1484–1486)'],
    ['What is Dadaism?', 'WWI-era anti-war, anti-bourgeois art movement questioning the role of art. Key figure: Marcel Duchamp'],
    ['What is the Renaissance?', '14th–17th century European revival of classical learning and art. Key figures: Leonardo, Michelangelo, Raphael'],
    ['Who painted "Guernica"?', 'Pablo Picasso (1937) — response to bombing of Guernica in the Spanish Civil War'],
    ['What is Pointillism?', 'Painting with small dots of pure color. Key artist: Georges Seurat ("A Sunday on La Grande Jatte")'],
    ['Who is Frida Kahlo?', 'Mexican painter (1907–1954) known for self-portraits blending personal pain and Mexican folk art'],
    ['What is the Bauhaus?', 'German art school (1919–1933) that combined fine art with functional design'],
    ['Who sculpted "David"?', 'Michelangelo (1501–1504), marble, Florence'],
    ['What is Pop Art?', '1950s–60s movement using commercial imagery. Key artists: Andy Warhol, Roy Lichtenstein'],
    ['Who is Auguste Rodin?', 'French sculptor (1840–1917); known for "The Thinker" and "The Kiss"'],
    ['What is Expressionism?', 'Early 20th century; distorted forms to convey emotion. Key artists: Edvard Munch ("The Scream"), Kirchner'],
  ]),

  deck('geography', '🗺️ World Geography', [
    ['Longest river in the world', 'Nile River (Africa) — ~6,650 km'],
    ['Largest ocean', 'Pacific Ocean — covers ~165 million km²'],
    ['Highest mountain in the world', 'Mount Everest — 8,849 m (Himalayas, Nepal/Tibet)'],
    ['Largest desert in the world', 'Antarctic Desert (cold) — 14.2 million km². Largest hot desert: Sahara'],
    ['Deepest ocean trench', 'Mariana Trench (Pacific) — ~11,034 m deep'],
    ['Largest country by area', 'Russia — 17.1 million km²'],
    ['Most populous country', 'India (surpassed China in 2023)'],
    ['Smallest country in the world', 'Vatican City — 0.44 km²'],
    ['Longest mountain range', 'Andes (South America) — ~7,000 km'],
    ['Largest rainforest', 'Amazon Rainforest (South America) — ~5.5 million km²'],
    ['Which continent has the most countries?', 'Africa — 54 countries'],
    ['What is the Ring of Fire?', 'Horseshoe-shaped zone around the Pacific with most of the world\'s volcanic activity and earthquakes'],
    ['What is the Great Barrier Reef?', 'World\'s largest coral reef system, off Queensland, Australia (~2,300 km long)'],
    ['Largest lake in the world', 'Caspian Sea — technically a landlocked salt lake (~371,000 km²)'],
    ['What are the BRICS countries?', 'Brazil, Russia, India, China, South Africa — major emerging economies'],
    ['What is the Sahel?', 'Semi-arid belt across Africa south of the Sahara — prone to desertification and drought'],
    ['What is the International Date Line?', '180° meridian — crossing it moves you forward or back one calendar day'],
    ['Which country has the most official languages?', 'Zimbabwe — 16 official languages'],
    ['What is the Dead Sea?', 'Saltiest large body of water (~34% salinity), ~430 m below sea level'],
    ['Which ocean is bounded by the Arctic and Antarctic circles?', 'Both the Arctic Ocean (north) and Southern Ocean (south)'],
  ]),

  deck('mythology', '⚡ Greek & Roman Mythology', [
    ['Zeus (Jupiter) — domain', 'King of the Olympian gods; sky, lightning, thunder'],
    ['Hera (Juno) — domain', 'Queen of the gods; marriage, women, childbirth'],
    ['Poseidon (Neptune) — domain', 'Sea, earthquakes, horses'],
    ['Athena (Minerva) — domain', 'Wisdom, warfare strategy, crafts. Born fully armed from Zeus\'s head'],
    ['Apollo (Apollo) — domain', 'Sun, music, poetry, prophecy, medicine'],
    ['Artemis (Diana) — domain', 'Moon, hunting, wilderness. Apollo\'s twin'],
    ['Ares (Mars) — domain', 'War, violence, bloodshed'],
    ['Aphrodite (Venus) — domain', 'Love, beauty, desire. Born from sea foam'],
    ['Hermes (Mercury) — domain', 'Messenger of the gods; commerce, thieves, travel, guide of souls'],
    ['Hephaestus (Vulcan) — domain', 'Fire, metalworking, crafts. The divine blacksmith'],
    ['Demeter (Ceres) — domain', 'Agriculture, harvest, fertility. Mother of Persephone'],
    ['Dionysus (Bacchus) — domain', 'Wine, festivity, ecstasy, theatre'],
    ['What is the myth of Prometheus?', 'Titan who stole fire from the gods and gave it to humans; punished by Zeus (chained, eagle ate his liver daily)'],
    ['What is the myth of Icarus?', 'Flew too close to the sun with wax wings made by his father Daedalus; wings melted, he fell into the sea'],
    ['What is the Trojan War?', '10-year war between Greeks and Troy over Helen; ended with the Trojan Horse stratagem'],
    ['Who was Odysseus (Ulysses)?', 'King of Ithaca; hero of Homer\'s Odyssey — 10-year journey home after the Trojan War'],
    ['What is the myth of Narcissus?', 'Beautiful youth who fell in love with his own reflection and wasted away (origin of "narcissism")'],
    ['Who is Medusa?', 'Gorgon with snakes for hair; gaze turned people to stone; slain by Perseus'],
    ['What is the myth of Orpheus?', 'Musician who descended to the underworld to retrieve his wife Eurydice; failed by looking back'],
    ['Who is Heracles (Hercules)?', 'Greatest Greek hero; son of Zeus; known for the Twelve Labors'],
  ]),

  deck('classical-music', '🎼 Classical Composers & Works', [
    ['Who composed the "Four Seasons"?', 'Antonio Vivaldi (c. 1720) — four violin concertos representing the seasons'],
    ['Who composed Symphony No. 9 "Choral"?', 'Ludwig van Beethoven (1824) — composed while deaf; includes "Ode to Joy"'],
    ['Who composed "The Magic Flute"?', 'Wolfgang Amadeus Mozart (1791)'],
    ['Who composed "The Messiah"?', 'George Frideric Handel (1741) — includes the famous "Hallelujah Chorus"'],
    ['Who composed "The Well-Tempered Clavier"?', 'Johann Sebastian Bach (1722) — 48 preludes and fugues in all keys'],
    ['Who composed "The Rite of Spring"?', 'Igor Stravinsky (1913) — its Paris premiere caused a near-riot'],
    ['Who composed "Clair de Lune"?', 'Claude Debussy (Suite bergamasque, 1905) — Impressionist piano piece'],
    ['What is the Classical period in music?', 'c. 1750–1820; Haydn, Mozart, early Beethoven; clarity, balance, structure'],
    ['What is the Romantic period in music?', 'c. 1820–1900; Beethoven, Brahms, Chopin, Liszt, Wagner; emotional expression, nationalism'],
    ['Who composed the "1812 Overture"?', 'Pyotr Ilyich Tchaikovsky (1880) — celebrating Russia\'s defeat of Napoleon'],
    ['Who composed "Für Elise"?', 'Ludwig van Beethoven (c. 1810) — bagatelle in A minor'],
    ['Who composed the Brandenburg Concertos?', 'Johann Sebastian Bach (1721)'],
    ['Who is Frédéric Chopin?', 'Polish Romantic composer (1810–1849); known for nocturnes, études, and mazurkas for piano'],
    ['Who is Franz Liszt?', 'Hungarian Romantic composer (1811–1886); known for technical virtuosity and symphonic poems'],
    ['What is a fugue?', 'A contrapuntal composition where a short melody (subject) is introduced and developed by successive voices; perfected by Bach'],
    ['Who composed "Don Giovanni"?', 'Wolfgang Amadeus Mozart (1787)'],
    ['What are the Goldberg Variations?', 'Bach\'s keyboard work (1741) — 30 variations on an aria; basis of counterpoint mastery'],
    ['Who composed "Swan Lake"?', 'Pyotr Ilyich Tchaikovsky (1875–1876)'],
    ['What is an oratorio?', 'Large-scale vocal work for chorus, soloists, and orchestra on sacred or epic text; no staging (unlike opera)'],
    ['Who composed "Boléro"?', 'Maurice Ravel (1928) — single melody with relentless crescendo over a constant rhythm'],
  ]),

  deck('english-vocabulary', '📝 Academic Vocabulary', [
    ['Ephemeral', 'Lasting for only a short time; transitory ("ephemeral fame")'],
    ['Ubiquitous', 'Present, appearing, or found everywhere ("smartphones are ubiquitous")'],
    ['Ambiguous', 'Open to more than one interpretation; unclear'],
    ['Empirical', 'Based on observation or experiment rather than theory'],
    ['Paradox', 'A statement that contradicts itself but may be true ("less is more")'],
    ['Hegemony', 'Leadership or dominance, especially of one country or group over others'],
    ['Pragmatic', 'Dealing with things practically rather than theoretically'],
    ['Rhetoric', 'The art of effective or persuasive speaking or writing'],
    ['Synthesis', 'The combination of elements to form a connected whole'],
    ['Juxtaposition', 'Placing two things close together to highlight contrast'],
    ['Anachronism', 'A thing out of its proper historical time ("a knight with a smartphone")'],
    ['Catharsis', 'Relief from strong emotions through art; from Aristotle\'s Poetics'],
    ['Dystopia', 'An imagined society that is dehumanizing or frightening (opposite of utopia)'],
    ['Allegory', 'A story with a hidden symbolic meaning beyond the literal one'],
    ['Metaphor', 'A figure of speech applying a word/phrase to something it doesn\'t literally denote to suggest resemblance'],
    ['Irony', 'Expression of meaning through language that normally signifies the opposite'],
    ['Dichotomy', 'A division into two contradictory or mutually exclusive parts'],
    ['Solipsism', 'The view that only one\'s own mind is certain to exist'],
    ['Catharsis', 'Emotional release or purification through art or experience'],
    ['Epistemology', 'The branch of philosophy concerned with the theory of knowledge'],
  ]),

  deck('biology', '🧬 Biology Essentials', [
    ['What is the cell theory?', '1. All living things are made of cells. 2. The cell is the basic unit of life. 3. All cells arise from pre-existing cells.'],
    ['What is photosynthesis?', '6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂ (glucose and oxygen produced from CO₂ and water)'],
    ['What is cellular respiration?', 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP (glucose broken down to release energy)'],
    ['What does DNA stand for?', 'Deoxyribonucleic acid — stores genetic information'],
    ['What are the four DNA bases?', 'Adenine (A), Thymine (T), Guanine (G), Cytosine (C). A pairs with T; G pairs with C'],
    ['What is natural selection?', 'Organisms with heritable traits better suited to their environment survive and reproduce more — Darwin\'s mechanism for evolution'],
    ['What is mitosis?', 'Cell division producing two genetically identical daughter cells (for growth and repair)'],
    ['What is meiosis?', 'Cell division producing four genetically unique cells with half the chromosomes (for sexual reproduction)'],
    ['What are the kingdoms of life?', 'Animalia, Plantae, Fungi, Protista, Archaea, Bacteria (6-kingdom system)'],
    ['What is a eukaryote?', 'Cell with a membrane-bound nucleus. Includes animals, plants, fungi, and protists'],
    ['What is a prokaryote?', 'Cell without a membrane-bound nucleus. Includes bacteria and archaea'],
    ['What is an enzyme?', 'A biological catalyst (protein) that speeds up chemical reactions without being consumed'],
    ['What is homeostasis?', 'The tendency of a living system to maintain a stable internal environment'],
    ['What is a chromosome?', 'Thread-like structure of DNA and protein carrying genetic information; humans have 46 (23 pairs)'],
    ['What is a gene?', 'A sequence of DNA that codes for a specific protein or has a specific function'],
    ['What is the central dogma of molecular biology?', 'DNA → (transcription) → RNA → (translation) → Protein'],
    ['What is an ecosystem?', 'All living organisms in an area and their interactions with each other and their physical environment'],
    ['What is biodiversity?', 'The variety of life in a region — includes genetic, species, and ecosystem diversity'],
    ['What is a food chain?', 'Linear sequence showing energy transfer from producers to consumers'],
    ['What are stem cells?', 'Undifferentiated cells that can develop into specialized cell types; key to development and regeneration'],
  ]),

  deck('physics', '⚛️ Physics Fundamentals', [
    ['Newton\'s First Law', 'An object at rest stays at rest; an object in motion stays in motion unless acted on by an external force (law of inertia)'],
    ['Newton\'s Second Law', 'F = ma (force = mass × acceleration)'],
    ['Newton\'s Third Law', 'For every action there is an equal and opposite reaction'],
    ['What is the speed of light?', 'c ≈ 3 × 10⁸ m/s (299,792,458 m/s in a vacuum)'],
    ['What is E = mc²?', 'Mass-energy equivalence: energy equals mass times the speed of light squared (Einstein, 1905)'],
    ['What is the law of conservation of energy?', 'Energy cannot be created or destroyed — only transformed from one form to another'],
    ['What is Ohm\'s Law?', 'V = IR (voltage = current × resistance)'],
    ['What is the Doppler effect?', 'The change in frequency of a wave as the source and observer move relative to each other (e.g., siren pitch changing)'],
    ['What is entropy?', 'A measure of disorder in a system; the universe tends toward greater entropy (second law of thermodynamics)'],
    ['What is gravity?', 'A force of attraction between masses; Newton: F = Gm₁m₂/r². Einstein: curvature of spacetime'],
    ['What is the electromagnetic spectrum?', 'Full range of EM radiation: radio → microwave → infrared → visible → UV → X-ray → gamma ray'],
    ['What is a photon?', 'The quantum of electromagnetic radiation; massless particle carrying light energy'],
    ['What is absolute zero?', '0 K = −273.15°C — the lowest theoretical temperature where particles have minimum thermal energy'],
    ['What is terminal velocity?', 'The constant speed reached when drag force equals gravitational force on a falling object'],
    ['What is wavelength?', 'The distance between successive crests of a wave; λ = v/f'],
    ['What is nuclear fission?', 'Splitting a heavy nucleus into smaller nuclei, releasing large amounts of energy (used in nuclear power/bombs)'],
    ['What is nuclear fusion?', 'Joining light nuclei to form a heavier nucleus, releasing enormous energy (powers stars)'],
    ['What is the Bohr model?', 'Model of the atom where electrons orbit the nucleus in fixed energy shells (1913)'],
    ['What is momentum?', 'p = mv (mass × velocity). Momentum is conserved in closed systems.'],
    ['What is the Heisenberg uncertainty principle?', 'You cannot simultaneously know both the exact position and exact momentum of a particle with perfect precision'],
  ]),

  deck('music-notes', '🎵 Reading Musical Notes', [
    ['What is the treble clef also called?', 'G clef — the curl wraps around the G line (second line from bottom of the staff)'],
    ['What is the bass clef also called?', 'F clef — the two dots surround the F line (fourth line from bottom)'],
    ['Notes on the treble clef lines (bottom to top)', 'E G B D F — "Every Good Boy Does Fine"'],
    ['Notes in the treble clef spaces (bottom to top)', 'F A C E — spells "FACE"'],
    ['Notes on the bass clef lines (bottom to top)', 'G B D F A — "Good Boys Do Fine Always"'],
    ['Notes in the bass clef spaces (bottom to top)', 'A C E G — "All Cows Eat Grass"'],
    ['What is middle C?', 'C4 — sits on the ledger line between the treble and bass staves; first ledger line below treble clef'],
    ['What is a whole note?', '4 beats in 4/4 time — open oval with no stem'],
    ['What is a half note?', '2 beats — open oval with a stem'],
    ['What is a quarter note?', '1 beat — filled oval with a stem'],
    ['What is an eighth note?', '½ beat — filled oval with a stem and one flag (or beam)'],
    ['What is a sixteenth note?', '¼ beat — filled oval with a stem and two flags'],
    ['What is a dotted note?', 'A dot after a note adds half its value (e.g., dotted half = 3 beats)'],
    ['What is a rest?', 'A symbol indicating silence for a specific duration (whole, half, quarter, eighth rests)'],
    ['What does 4/4 time signature mean?', '4 beats per measure; quarter note gets one beat — the most common time signature'],
    ['What does 3/4 time signature mean?', '3 beats per measure; quarter note gets one beat — waltz time'],
    ['What does 6/8 time signature mean?', '6 eighth-note beats per measure, grouped in two sets of 3 — compound duple'],
    ['What is a sharp (♯)?', 'Raises a note by one semitone (half step)'],
    ['What is a flat (♭)?', 'Lowers a note by one semitone (half step)'],
    ['What is a natural (♮)?', 'Cancels a previous sharp or flat, returning the note to its original pitch'],
    ['What is a key signature?', 'Sharps or flats placed at the beginning of the staff indicating the key of the piece'],
    ['What is the order of sharps in key signatures?', 'F C G D A E B — "Fat Cats Go Down Alleys Eating Birds"'],
    ['What is the order of flats in key signatures?', 'B E A D G C F — reverse of sharps — "Battle Ends And Down Goes Charles\'s Father"'],
    ['What is C major?', 'Scale: C D E F G A B C — no sharps or flats'],
    ['What is G major?', 'Scale with one sharp: F♯'],
    ['What is F major?', 'Scale with one flat: B♭'],
    ['What is a scale?', 'A sequence of notes in ascending or descending order following a pattern of whole (W) and half (H) steps; major pattern: W W H W W W H'],
    ['What is an octave?', 'The interval between one pitch and another with double its frequency — 8 notes apart (e.g., C4 to C5)'],
    ['What is a chord?', 'Three or more notes played simultaneously; a triad consists of a root, third, and fifth'],
    ['What is tempo?', 'The speed of music; common markings: Largo (slow) → Andante → Moderato → Allegro → Presto (fast)'],
  ]),

  deck('swahili-1', '🇰🇪 Swahili: Greetings, Phrases & Travel', [
    // Greetings
    ['Habari?', 'How are you? — Reply: Nzuri / Sawa / Salama'],
    ['Habari yako?', 'How are you? (singular) — same as Habari?'],
    ['Habari zenu?', 'How are you? (plural / group)'],
    ['Hujambo?', 'Hello / How do you do? (to one) — Reply: Sijambo'],
    ['Hamjambo?', 'Hello (to a group) — Reply: Hatujambo'],
    ['Jambo!', 'Hello! (informal, to anyone)'],
    ['Habari za asubuhi', 'Good morning'],
    ['Habari za mchana', 'Good afternoon'],
    ['Habari za jioni', 'Good evening'],
    ['Lala salama', 'Good night / Sleep peacefully'],
    ['Asante', 'Thank you'],
    ['Asante sana', 'Thank you very much'],
    ['Karibu / Karibu sana', "You're welcome / You're very welcome"],
    ['Tafadhali', 'Please'],
    ['Samahani', 'Excuse me / Sorry'],
    ['Pole', 'Sorry / Condolences (sympathy)'],
    ['Pole sana', 'I\'m very sorry'],
    ['Ndiyo', 'Yes'],
    ['Hapana / La', 'No'],
    ['Sawa', 'OK / Fine / Alright'],
    ['Sawa sawa', 'OK OK / No problem'],
    ['Kwaheri', 'Goodbye (to one)'],
    ['Kwaherini', 'Goodbye (to many)'],
    ['Tutaonana', 'See you later / We\'ll meet again'],
    ['Tutaonana baadaye', 'See you later'],
    ['Karibu tena', 'Welcome back / Come again'],
    ['Hongera', 'Congratulations'],
    ['Bahati njema', 'Good luck'],
    ['Msaada!', 'Help!'],
    // Introductions
    ['Jina lako nani?', 'What is your name? — Reply: Jina langu ni…'],
    ['Jina langu ni…', 'My name is…'],
    ['Unatoka wapi?', 'Where are you from? — Reply: Natoka…'],
    ['Natoka Kenya', 'I am from Kenya'],
    ['Unaishi wapi?', 'Where do you live?'],
    ['Ninaishi Nairobi', 'I live in Nairobi'],
    ['Una miaka mingapi?', 'How old are you?'],
    ['Nina miaka kumi na nane', 'I am eighteen years old'],
    ['Unafanya kazi gani?', 'What work do you do?'],
    ['Mimi ni mwanafunzi', 'I am a student'],
    ['Mimi ni mwalimu', 'I am a teacher'],
    ['Nimefurahi kukuona', 'Nice to meet you'],
    // Language
    ['Unasema Kiingereza?', 'Do you speak English?'],
    ['Unasema Kiswahili?', 'Do you speak Swahili?'],
    ['Nasema kidogo Kiswahili', 'I speak a little Swahili'],
    ['Sisemi Kiswahili vizuri', 'I don\'t speak Swahili well'],
    ['Sielewi', 'I don\'t understand'],
    ['Naelewa', 'I understand'],
    ['Sema tena, tafadhali', 'Please say that again'],
    ['Sema polepole, tafadhali', 'Please speak slowly'],
    ['Maana yake nini?', 'What does it mean?'],
    ['...inaitwa nini kwa Kiswahili?', 'What is ... called in Swahili?'],
    ['Ninaenda...', 'I am going to...'],
    // Travel & Directions
    ['Wapi ni...?', 'Where is...?'],
    ['Iko wapi hospitali?', 'Where is the hospital?'],
    ['Iko wapi stendi?', 'Where is the bus station?'],
    ['Iko wapi benki?', 'Where is the bank?'],
    ['Iko wapi choo?', 'Where is the toilet?'],
    ['Nenda moja kwa moja', 'Go straight ahead'],
    ['Geuka kushoto', 'Turn left'],
    ['Geuka kulia', 'Turn right'],
    ['Mbali / Karibu', 'Far / Near'],
    ['Nauli ni ngapi?', 'How much is the fare?'],
    ['Tiketi moja, tafadhali', 'One ticket, please'],
    ['Simama hapa', 'Stop here'],
    ['Nataka kwenda...', 'I want to go to...'],
    ['Gari la moshi', 'Train (literally "smoke car")'],
    ['Basi', 'Bus'],
    ['Pikipiki', 'Motorcycle'],
    ['Bahari', 'Sea / Ocean'],
    ['Uwanja wa ndege', 'Airport'],
    // Shopping & Money
    ['Bei gani?', 'How much does it cost?'],
    ['Ni ghali sana', 'It is very expensive'],
    ['Punguza bei', 'Reduce the price'],
    ['Nataka kununua...', 'I want to buy...'],
    ['Nina njaa', 'I am hungry'],
    ['Nina kiu', 'I am thirsty'],
    ['Nataka chakula', 'I want food'],
    ['Nataka maji', 'I want water'],
    ['Bila sukari', 'Without sugar'],
    ['Tena moja', 'One more'],
    ['Hesabu, tafadhali', 'The bill, please'],
    // Emergencies
    ['Daktari!', 'Doctor!'],
    ['Wezi!', 'Thief!'],
    ['Moto!', 'Fire!'],
    ['Polisi!', 'Police!'],
    ['Naumwa', 'I am sick / I am in pain'],
    ['Naumwa tumbo', 'I have a stomach ache'],
    ['Piga simu polisi', 'Call the police'],
  ]),

  deck('swahili-2', '🔢 Swahili: Numbers, Time, Calendar & Colors', [
    // Numbers 1–20
    ['moja', '1'],
    ['mbili', '2'],
    ['tatu', '3'],
    ['nne', '4'],
    ['tano', '5'],
    ['sita', '6'],
    ['saba', '7'],
    ['nane', '8'],
    ['tisa', '9'],
    ['kumi', '10'],
    ['kumi na moja', '11'],
    ['kumi na mbili', '12'],
    ['kumi na tatu', '13'],
    ['kumi na nne', '14'],
    ['kumi na tano', '15'],
    ['kumi na sita', '16'],
    ['kumi na saba', '17'],
    ['kumi na nane', '18'],
    ['kumi na tisa', '19'],
    ['ishirini', '20'],
    // Tens & large
    ['thelathini', '30'],
    ['arobaini', '40'],
    ['hamsini', '50'],
    ['sitini', '60'],
    ['sabini', '70'],
    ['themanini', '80'],
    ['tisini', '90'],
    ['mia moja', '100'],
    ['mia mbili', '200'],
    ['elfu moja', '1,000'],
    ['elfu kumi', '10,000'],
    ['laki moja', '100,000'],
    ['milioni moja', '1,000,000'],
    // Ordinals
    ['ya kwanza', '1st (first)'],
    ['ya pili', '2nd (second)'],
    ['ya tatu', '3rd (third)'],
    ['ya mwisho', 'last'],
    // Time concepts
    ['Saa ngapi?', 'What time is it? — Note: Swahili clock is offset by 6h (7am = Saa moja)'],
    ['Saa moja asubuhi', '7:00 AM'],
    ['Saa mbili asubuhi', '8:00 AM'],
    ['Saa sita mchana', '12:00 noon'],
    ['Saa saba mchana', '1:00 PM'],
    ['Saa kumi na mbili usiku', '6:00 PM'],
    ['Asubuhi', 'Morning'],
    ['Mchana', 'Midday / Afternoon'],
    ['Jioni', 'Evening'],
    ['Usiku', 'Night'],
    ['Sasa hivi', 'Right now'],
    ['Baadaye', 'Later'],
    ['Mapema', 'Early'],
    ['Kuchelewa', 'Late / To be late'],
    ['Dakika', 'Minute'],
    ['Saa', 'Hour / Clock / Watch'],
    // Days of the week
    ['Jumatatu', 'Monday'],
    ['Jumanne', 'Tuesday'],
    ['Jumatano', 'Wednesday'],
    ['Alhamisi', 'Thursday'],
    ['Ijumaa', 'Friday'],
    ['Jumamosi', 'Saturday'],
    ['Jumapili', 'Sunday'],
    // Time words
    ['Leo', 'Today'],
    ['Jana', 'Yesterday'],
    ['Kesho', 'Tomorrow'],
    ['Juzi', 'The day before yesterday'],
    ['Kesho kutwa', 'The day after tomorrow'],
    ['Wiki hii', 'This week'],
    ['Wiki iliyopita', 'Last week'],
    ['Wiki ijayo', 'Next week'],
    ['Mwezi', 'Month'],
    ['Mwaka', 'Year'],
    ['Mwaka huu', 'This year'],
    ['Mwaka uliopita', 'Last year'],
    ['Miaka mingi', 'Many years'],
    // Months
    ['Januari', 'January'],
    ['Februari', 'February'],
    ['Machi', 'March'],
    ['Aprili', 'April'],
    ['Mei', 'May'],
    ['Juni', 'June'],
    ['Julai', 'July'],
    ['Agosti', 'August'],
    ['Septemba', 'September'],
    ['Oktoba', 'October'],
    ['Novemba', 'November'],
    ['Desemba', 'December'],
    // Colors
    ['nyekundu', 'red'],
    ['bluu / samawati', 'blue / sky blue'],
    ['kijani (kibichi)', 'green'],
    ['njano', 'yellow'],
    ['nyeupe', 'white'],
    ['nyeusi', 'black'],
    ['kahawia', 'brown'],
    ['rangi ya machungwa', 'orange'],
    ['rangi ya waridi', 'pink'],
    ['zambarau', 'purple'],
    ['kijivu', 'grey'],
    ['fedha', 'silver'],
    ['dhahabu', 'gold'],
    // Weather
    ['Hali ya hewa', 'Weather'],
    ['Jua', 'Sun / Sunshine'],
    ['Mvua', 'Rain'],
    ['Upepo', 'Wind'],
    ['Baridi', 'Cold'],
    ['Joto', 'Heat / Hot'],
    ['Theluji', 'Snow'],
    ['Wingu / Mawingu', 'Cloud / Clouds'],
    ['Umeme', 'Lightning / Electricity'],
    ['Radi', 'Thunder'],
    ['Leo ni joto', 'Today is hot'],
    ['Mvua inanyesha', 'It is raining'],
    ['Hewa ni safi', 'The air is clean / fresh'],
  ]),

  deck('swahili-3', '🗣️ Swahili: Nouns, Verbs & Adjectives', [
    // People & Family
    ['mtu / watu', 'person / people'],
    ['mtoto / watoto', 'child / children'],
    ['mwanamke / wanawake', 'woman / women'],
    ['mwanamume / wanaume', 'man / men'],
    ['mvulana / wavulana', 'boy / boys'],
    ['msichana / wasichana', 'girl / girls'],
    ['familia', 'family'],
    ['mama', 'mother'],
    ['baba', 'father'],
    ['kaka', 'older brother'],
    ['dada', 'older sister'],
    ['ndugu', 'sibling / relative / comrade'],
    ['babu', 'grandfather'],
    ['bibi', 'grandmother / Miss / Mrs'],
    ['mjomba', 'uncle (mother\'s brother)'],
    ['shangazi', 'aunt (father\'s sister)'],
    ['bwana', 'Mr / sir / husband'],
    ['mke / wake', 'wife / wives'],
    ['mume / waume', 'husband / husbands'],
    ['rafiki / marafiki', 'friend / friends'],
    ['jirani / majirani', 'neighbour / neighbours'],
    ['mgeni / wageni', 'guest / guests / stranger'],
    // Body parts
    ['kichwa', 'head'],
    ['nywele', 'hair'],
    ['uso', 'face'],
    ['jicho / macho', 'eye / eyes'],
    ['sikio / masikio', 'ear / ears'],
    ['pua', 'nose'],
    ['mdomo / midomo', 'mouth / mouths'],
    ['meno', 'teeth'],
    ['ulimi', 'tongue'],
    ['shingo', 'neck'],
    ['bega / mabega', 'shoulder / shoulders'],
    ['mkono / mikono', 'hand / arm / hands'],
    ['kidole / vidole', 'finger / fingers'],
    ['mguu / miguu', 'foot / leg / feet'],
    ['tumbo', 'stomach / belly'],
    ['moyo', 'heart'],
    ['damu', 'blood'],
    ['ngozi', 'skin'],
    // Home & Objects
    ['nyumba', 'house / home'],
    ['mlango', 'door'],
    ['dirisha / madirisha', 'window / windows'],
    ['ukuta / kuta', 'wall / walls'],
    ['dari', 'floor / storey'],
    ['dari ya juu', 'upstairs / upper floor'],
    ['meza', 'table'],
    ['kiti / viti', 'chair / chairs'],
    ['kitanda / vitanda', 'bed / beds'],
    ['jiko / meko', 'stove / stoves'],
    ['chombo / vyombo', 'utensil / tools'],
    ['sahani', 'plate / dish'],
    ['kikombe / vikombe', 'cup / cups'],
    ['kisu / visu', 'knife / knives'],
    ['uma / nyuma', 'fork'],
    ['kijiko / vijiko', 'spoon / spoons'],
    ['mfuko / mifuko', 'bag / pocket / bags'],
    ['nguo / mavazi', 'clothes / clothing'],
    ['kofia', 'hat / cap'],
    ['viatu', 'shoes'],
    // Food & Drink
    ['chakula', 'food'],
    ['maji', 'water'],
    ['mkate', 'bread'],
    ['nyama', 'meat'],
    ['kuku', 'chicken'],
    ['samaki', 'fish'],
    ['mayai', 'eggs'],
    ['mboga', 'vegetables'],
    ['matunda', 'fruit'],
    ['ndizi', 'banana'],
    ['embe / maembe', 'mango / mangoes'],
    ['machungwa', 'orange(s)'],
    ['nazi', 'coconut'],
    ['wali', 'cooked rice'],
    ['ugali', 'maize porridge (staple food)'],
    ['maharagwe', 'beans'],
    ['sukari', 'sugar'],
    ['chumvi', 'salt'],
    ['mafuta', 'oil / fat / fuel'],
    ['maziwa', 'milk'],
    ['chai', 'tea'],
    ['kahawa', 'coffee'],
    ['juisi', 'juice'],
    ['bia', 'beer'],
    ['mvinyo', 'wine'],
    // Places
    ['shule', 'school'],
    ['chuo', 'college / university'],
    ['hospitali', 'hospital'],
    ['kanisa', 'church'],
    ['msikiti', 'mosque'],
    ['duka / maduka', 'shop / shops'],
    ['soko / masoko', 'market / markets'],
    ['benki', 'bank'],
    ['hoteli', 'hotel / restaurant'],
    ['ofisi', 'office'],
    ['polisi', 'police station / police'],
    ['uwanja', 'field / stadium / airport'],
    ['bustani', 'garden / park'],
    ['barabara', 'road / street'],
    ['mji / miji', 'town / city / towns'],
    ['kijiji / vijiji', 'village / villages'],
    ['nchi', 'country'],
    ['pwani', 'coast / beach'],
    ['mlima / milima', 'mountain / mountains'],
    ['mto / mito', 'river / rivers'],
    ['ziwa / maziwa', 'lake / lakes'],
    ['msitu / misitu', 'forest / forests'],
    // Animals
    ['simba', 'lion'],
    ['tembo', 'elephant'],
    ['twiga', 'giraffe'],
    ['nyati', 'buffalo'],
    ['kiboko', 'hippopotamus'],
    ['fisi', 'hyena'],
    ['mbweha', 'fox / jackal'],
    ['chui', 'leopard'],
    ['duma', 'cheetah'],
    ['nyoka', 'snake'],
    ['mamba', 'crocodile'],
    ['ndege', 'bird / airplane'],
    ['tai', 'eagle'],
    ['mbuni', 'ostrich'],
    ['samaki', 'fish'],
    ['mbwa', 'dog'],
    ['paka', 'cat'],
    ['ng\'ombe / ng\'ombe', 'cow / cattle'],
    ['kondoo', 'sheep'],
    ['mbuzi', 'goat'],
    ['farasi', 'horse'],
    ['punda', 'donkey'],
    ['nguruwe', 'pig'],
    // Key Verbs (infinitive = ku- prefix)
    ['kusema', 'to speak / to say'],
    ['kusikia', 'to hear / to feel'],
    ['kuona', 'to see'],
    ['kujua', 'to know'],
    ['kuelewa', 'to understand'],
    ['kusahau', 'to forget'],
    ['kukumbuka', 'to remember'],
    ['kufikiria', 'to think'],
    ['kupenda', 'to love / to like'],
    ['kuchukia', 'to hate'],
    ['kutaka', 'to want'],
    ['kuhitaji', 'to need'],
    ['kwenda', 'to go'],
    ['kuja', 'to come'],
    ['kurudi', 'to return'],
    ['kukimbia', 'to run'],
    ['kutembea', 'to walk'],
    ['kukaa', 'to stay / to sit'],
    ['kulala', 'to sleep'],
    ['kuamka', 'to wake up'],
    ['kula', 'to eat'],
    ['kunywa', 'to drink'],
    ['kupika', 'to cook'],
    ['kununua', 'to buy'],
    ['kuuza', 'to sell'],
    ['kulipa', 'to pay'],
    ['kufungua', 'to open'],
    ['kufunga', 'to close / to lock'],
    ['kusoma', 'to read / to study'],
    ['kuandika', 'to write'],
    ['kucheza', 'to play'],
    ['kufanya kazi', 'to work'],
    ['kusaidia', 'to help'],
    ['kuuliza', 'to ask'],
    ['kujibu', 'to answer / to reply'],
    ['kucheka', 'to laugh'],
    ['kulia', 'to cry'],
    ['kupigana', 'to fight'],
    ['kuomba', 'to pray / to request'],
    ['kupiga simu', 'to call (phone)'],
    ['kuimba', 'to sing'],
    ['kuchora', 'to draw'],
    ['kulima', 'to farm / to cultivate'],
    ['kuosha', 'to wash'],
    ['kuvaa', 'to wear / to dress'],
    // Adjectives
    ['nzuri', 'good / beautiful / fine'],
    ['baya / mbaya', 'bad'],
    ['kubwa', 'big / large'],
    ['ndogo', 'small / little'],
    ['ndefu', 'tall / long'],
    ['fupi', 'short'],
    ['nzito', 'heavy'],
    ['nyepesi', 'light (weight)'],
    ['haraka', 'fast / quickly'],
    ['polepole', 'slow / slowly'],
    ['mpya', 'new'],
    ['zamani / kongwe', 'old'],
    ['safi', 'clean'],
    ['chafu', 'dirty'],
    ['imara', 'strong / firm'],
    ['dhaifu', 'weak'],
    ['rahisi', 'easy / cheap'],
    ['ngumu', 'hard / difficult'],
    ['ghali', 'expensive'],
    ['tajiri', 'rich'],
    ['maskini', 'poor'],
    ['mgonjwa', 'sick / ill'],
    ['mzima', 'healthy / adult'],
    ['mzuri', 'well / good (person)'],
    ['wengi / mingi', 'many / much'],
    ['chache', 'few / little'],
    ['yote / zote', 'all (of them)'],
    ['sawa', 'equal / same / OK'],
    ['tofauti', 'different'],
    // Common question words
    ['nini?', 'what?'],
    ['nani?', 'who?'],
    ['wapi?', 'where?'],
    ['lini?', 'when?'],
    ['kwa nini?', 'why?'],
    ['vipi? / namna gani?', 'how?'],
    ['ngapi?', 'how many / how much?'],
  ]),
];
