"""Data models and schemas."""

from games.models.game import (
	GAME_DEFINITIONS,
	DebateTopic,
	GameDefinition,
	PatternPuzzle,
	Question,
	Subject,
	WritingPrompt,
	get_game_definition,
)
from games.models.progress import (
	BADGE_DEFINITIONS,
	Badge,
	BadgeType,
	GameProgress,
	LeaderboardEntry,
	PlayerProgress,
	SessionResult,
	SubjectProgress,
)
from games.models.session import (
	GAME_CATEGORY_MAP,
	ActiveGame,
	Difficulty,
	GameCategory,
	GameType,
	PlayerSession,
	Session,
	SessionCreate,
	SessionMode,
	SessionStatus,
	SessionUpdate,
)
from games.models.user import (
	ANIMAL_AVATARS,
	Team,
	TeamCode,
	TeamCreate,
	TeamJoin,
	TeamSwitch,
	User,
	UserCreate,
	UserRole,
	ScholarCodeLookup,
)

__all__ = [
	# User models
	"User",
	"UserRole",
	"UserCreate",
	"Team",
	"TeamCode",
	"TeamCreate",
	"TeamJoin",
	"TeamSwitch",
	"ScholarCodeLookup",
	"ANIMAL_AVATARS",
	# Session models
	"Session",
	"SessionCreate",
	"SessionUpdate",
	"SessionStatus",
	"SessionMode",
	"GameCategory",
	"GameType",
	"GAME_CATEGORY_MAP",
	"Difficulty",
	"ActiveGame",
	"PlayerSession",
	# Game models
	"Subject",
	"Question",
	"WritingPrompt",
	"DebateTopic",
	"PatternPuzzle",
	"GameDefinition",
	"GAME_DEFINITIONS",
	"get_game_definition",
	# Progress models
	"Badge",
	"BadgeType",
	"BADGE_DEFINITIONS",
	"SubjectProgress",
	"GameProgress",
	"PlayerProgress",
	"LeaderboardEntry",
	"SessionResult",
]
